config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users, skip: [:sessions]
  as :user do 
    post '/api/login' =>'sessions#create'
    put 'api/logout' => 'sessions#destroy_session'
    get 'api/menu' => 'menus#index'
  end

end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :task
  def ensure_authentication_token
  	self.authentication_token = generate_authentication_token
  	self.save!
  	self.authentication_token
  end
   def destroy_auth_token
    self.authentication_token = ""
    self.save!
  end
  private
  def generate_authentication_token
  	loop do
		token = Devise.friendly_token
		break token unless User.where(authentication_token: token).first  		
  	end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with:  :null_session
  def ensure_auth!
      puts request.headers["token"].presence
  	token = request.headers["token"].presence

  	user = token && User.find_by_authentication_token(token.to_s)
  	if user
  		sign_in user, store: false
      puts current_user
  	end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
before_action :ensure_auth!
	def index
		if current_user
			menu = Menu.all
			render json: menu
		else
			render json: {},status: :unauthorized
		end
	

	end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	before_action :ensure_auth!, only: [:destroy_session]
	skip_before_filter :verify_authenticity_token, :only => [:destroy_session]
	def create
		user = User.find_for_database_authentication(email: params[:email])
		
		if user && user.valid_password?(params[:password])
			token = user.ensure_authentication_token
			render json: {auth_token: token}
			
			
		else
			render nothing: true, status: :unauthorized	
		end
	end
	def destroy_session
		puts current_user.email
		if current_user
			current_user.destroy_auth_token
			render json: {data: "deleted"}
		else
			render nothing: true, status: :unauthorized
		end
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_auth!
  # GET /tasks
  # GET /tasks.json
  def index
    if current_user
      @tasks = Task.all
     else
      render json: {},status: :unauthorized
    end   
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    puts task_params
    @task = Task.new(task_params)
    puts @task
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      puts params
      #params[:todo]
      params.require(:task).permit(:todo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwBack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todo %><br>
    <%= f.text_field :todo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Todo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.todo %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todo:</strong>
  <%= @task.todo %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>